dist: jammy
language: python
install:
  - pip install .[test]
stages:
  - lint
  - test_11
  - test_12
jobs:
  include:
    - stage: lint
      python: "3.11"
      script:
        - pwd
        - pyproject-fmt --check .\pyproject.toml 
        - ssort --check .\src\ 
        - ruff format --check .\src\
        - mypy --show-error-codes -p upstage
    - stage: test_11
      python: "3.11"
      script: pytest
    - stage: test_12
      python: "3.12"
      script: pytest
