name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Analysing the code with pylint
      run: |
        pyproject-fmt --check pyproject.toml 
        ssort --check src
        ruff format --check src
        mypy --show-error-codes -p upstage

